name: my_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Null safety সাপোর্টের জন্য আপডেট করা হয়েছে

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  onboarding_screen: ^0.0.3
  introduction_screen: ^3.1.14
  liquid_progress_indicator_v2: ^0.5.0
  liquid_swipe: ^3.1.0
  salomon_bottom_bar: ^3.3.2
  water_drop_nav_bar: ^2.2.2
  animated_bottom_navigation_bar: ^1.3.3
  curved_navigation_bar: ^1.0.6
  get: ^4.6.5
  flutter_card_swiper: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
